### ISSUE TITLE
Python APIをVPSに設置，アクセスAPI作成

### ISSUE THREAD

**Issue by Sorarinu** [Sorarinu/ProjectP_Team#162]

**Comment by Sorarinu** [comment]
API URL（予定）: https://nxtg-t.net/api/v1/similarity-search/

**Comment by Sorarinu** [comment]
Laravel（PHP）→Python API→Laravel（PHP）→クライアント

**Comment by Koki07** [comment]
[memo]
現在のCentOSはPythonのVersionが2系なのでpyenvなどを使用して、3系に変える必要がある。
pyenvを用いる方法としては[ここ](http://qiita.com/saitou1978/items/e82421e29e118bd397cc)に記されている。
pipでinstallするmoduleのリストは[ここ](https://github.com/Sorarinu/ProjectP2016_F/blob/master/resemblance/pipList.md)にある

**Comment by Koki07** [comment]
pyenv入れました
virtualenvを使ってcloudBMという環境を作成しました

![image](https://cloud.githubusercontent.com/assets/7629228/20590498/b8e36584-b266-11e6-84a9-bed999605b91.png)

**Comment by Koki07** [comment]
MeCabのインストールは[これ](http://qiita.com/grachro/items/4fbc9bf8174c5abb7bdd)を参考に行います。

**Comment by Sorarinu** [comment]
Python APIはどれにリクエスト投げればいい感じ？

**Comment by Koki07** [comment]
similarityApplicationかな？

今pushした[シェルスクリプト](https://github.com/Sorarinu/ProjectP2016_F/blob/master/resemblance/main/similarity/prop-search.sh)みたいな感じ

> domain/api/v1/similarity-search/

で類似度検索できる。

**Comment by Sorarinu** [comment]
<img width="1440" alt="2016-11-25 15 39 30" src="https://cloud.githubusercontent.com/assets/16132069/20616401/6f0ea026-b325-11e6-8d6a-3a1b3469235f.png">
POST送るとエラー出る

**Comment by Sorarinu** [comment]
`ERROR in app: Exception on /api/v1/similarity-search/ [POST]
Traceback (most recent call last):
  File "/root/.pyenv/versions/cloudBM/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.pyenv/versions/cloudBM/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.pyenv/versions/cloudBM/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.pyenv/versions/cloudBM/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.pyenv/versions/cloudBM/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.pyenv/versions/cloudBM/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "similarityApplication.py", line 24, in __consumes
    return function(*argv, **keywords)
  File "similarityApplication.py", line 52, in similarity_search
    dict_data = add_flag()
  File "similarityApplication.py", line 42, in add_flag
    page = Scraping(bookmark_data['url']).create_scraping_file()
  File "/var/www/html/ProjectP2016_F/resemblance/main/similarity/api/search/scraping.py", line 31, in create_scraping_file
    str_list = self.get_body_text()
  File "/var/www/html/ProjectP2016_F/resemblance/main/similarity/api/search/scraping.py", line 22, in get_body_text
    soup = self.convert_html()
  File "/var/www/html/ProjectP2016_F/resemblance/main/similarity/api/search/scraping.py", line 17, in convert_html
    html = self.get_html()
  File "/var/www/html/ProjectP2016_F/resemblance/main/similarity/api/search/scraping.py", line 13, in get_html
    html = urllib.request.urlopen(self.url)
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 464, in open
    req = meth(req)
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 1176, in do_request_
    raise URLError('no host given')
urllib.error.URLError: <urlopen error no host given>
2016-11-25 15:39:13,047 : ERROR : Exception on /api/v1/similarity-search/ [POST]
Traceback (most recent call last):
  File "/root/.pyenv/versions/cloudBM/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.pyenv/versions/cloudBM/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.pyenv/versions/cloudBM/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.pyenv/versions/cloudBM/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/root/.pyenv/versions/cloudBM/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.pyenv/versions/cloudBM/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "similarityApplication.py", line 24, in __consumes
    return function(*argv, **keywords)
  File "similarityApplication.py", line 52, in similarity_search
    dict_data = add_flag()
  File "similarityApplication.py", line 42, in add_flag
    page = Scraping(bookmark_data['url']).create_scraping_file()
  File "/var/www/html/ProjectP2016_F/resemblance/main/similarity/api/search/scraping.py", line 31, in create_scraping_file
    str_list = self.get_body_text()
  File "/var/www/html/ProjectP2016_F/resemblance/main/similarity/api/search/scraping.py", line 22, in get_body_text
    soup = self.convert_html()
  File "/var/www/html/ProjectP2016_F/resemblance/main/similarity/api/search/scraping.py", line 17, in convert_html
    html = self.get_html()
  File "/var/www/html/ProjectP2016_F/resemblance/main/similarity/api/search/scraping.py", line 13, in get_html
    html = urllib.request.urlopen(self.url)
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 464, in open
    req = meth(req)
  File "/root/.pyenv/versions/3.5.2/lib/python3.5/urllib/request.py", line 1176, in do_request_
    raise URLError('no host given')
urllib.error.URLError: <urlopen error no host given>
127.0.0.1 - - [25/Nov/2016 15:39:13] "POST /api/v1/similarity-search/ HTTP/1.1" 500 -
2016-11-25 15:39:13,048 : INFO : 127.0.0.1 - - [25/Nov/2016 15:39:13] "POST /api/v1/similarity-search/ HTTP/1.1" 500 -`

エラー全文
